//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winform_imdb_crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.ParentalNotes = new HashSet<ParentalNote>();
        }
    
        public int Id { get; set; }
        public string Site { get; set; }
        public string MovieId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> Rating5star { get; set; }
        public Nullable<int> Rating10star { get; set; }
        public string ReccommendedAge { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewText { get; set; }
        public Nullable<int> UsefulnessNum { get; set; }
        public Nullable<int> UsefulnessOutOfNum { get; set; }
        public Nullable<int> HelpedDecideNum { get; set; }
        public Nullable<int> UsefulDetailNum { get; set; }
        public Nullable<int> ReadMyMindNum { get; set; }
        public string UserSex { get; set; }
        public Nullable<int> UserMinAge { get; set; }
        public Nullable<int> UserMaxAge { get; set; }
        public string CsmRoleRaw { get; set; }
        public string PageUrl { get; set; }
        public string ParentalNoteRaw { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ParentalNote> ParentalNotes { get; set; }
    }
}
