//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winform_imdb_crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public string Id { get; set; }
        public string Site { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> MemberSince { get; set; }
        public string PageUrl { get; set; }
        public string Location { get; set; }
        public string StatusAsAtCrawl { get; set; }
        public Nullable<int> NumOfRatings { get; set; }
        public Nullable<int> NumOfReviews { get; set; }
        public string RatingsAnalysisRaw { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
